### ISSUE TITLE
 Redesign led to increase in misplaced support requests in the contributor forums

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo-project#394] opened 2020-04-21 12:35 UTC
See relevant bug https://bugzilla.mozilla.org/show_bug.cgi?id=1631250

**Comment by akatsoulas** [comment] 2020-04-21 12:35
@jess-cook03 could you take a look at this?

**Comment by LeoMcA** [comment] 2020-04-21 13:51
duplicate of https://github.com/mozilla/sumo-project/issues/379

**Closed by LeoMcA** 2020-04-21 13:51 UTC
