### ISSUE TITLE
Messages are broken in the new UI

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo-project#101] opened 2020-01-02 13:48 UTC
Messages displayed in the top of the page are broken in the new designs. The following screenshot is from when users are logging in with their sumo account (non FxA).

![image](https://user-images.githubusercontent.com/900565/71670005-43331200-2d77-11ea-8387-6ba8113d0fcc.png)

**Comment by kkellydesign** [comment] 2020-01-02 20:00
This is fixed here: 
https://github.com/mozilla/sumo-project/issues/101

<img width="914" alt="Screen Shot 2020-01-02 at 2 55 48 PM" src="https://user-images.githubusercontent.com/202590/71689643-99e91d80-2d70-11ea-9ab2-b75cd358acec.png">

**Comment by akatsoulas** [comment] 2020-01-03 16:57
Final fix 
https://github.com/mozilla/kitsune/pull/4107

**Comment by viorelaioia** [comment] 2020-01-17 14:55
I looks good, but I'd like @jess-cook03 to take a look as well.
The error message looks like below, not sure if there are any designs for this. 

![image](https://user-images.githubusercontent.com/5293100/72621512-10c60f00-394a-11ea-9280-2980989a4516.png)

**Comment by jess-cook03** [comment] 2020-01-17 21:23
@viorelaioia @akatsoulas 
[Zeplin link](https://zpl.io/V49n8Jz)
We have newer styles for this within the new UI for the redesign.. if we can apply this here that would be awesome!
Screenshot:
<img width="1137" alt="Screen Shot 2020-01-17 at 4 21 41 PM" src="https://user-images.githubusercontent.com/54991698/72647060-9c896c80-3945-11ea-98ad-aacb149feecc.png">

**Comment by jess-cook03** [comment] 2020-01-17 21:29
@viorelaioia @akatsoulas the placement and alignment seems off -- making sure its aligned with the content of the page see screenshot below:
![72621512-10c60f00-394a-11ea-9280-2980989a4516](https://user-images.githubusercontent.com/54991698/72647396-7d3f0f00-3946-11ea-9ad0-651cb39eea05.png)

**Comment by kkellydesign** [comment] 2020-01-30 13:48
This is in. 

<img width="1352" alt="Screen Shot 2020-01-30 at 8 44 16 AM" src="https://user-images.githubusercontent.com/202590/73454771-c165e280-433c-11ea-9a30-3e0c67512121.png">

**Comment by ovidiuboca1** [comment] 2020-02-04 15:44
Tested on https://test.sumo.mozit.cloud/en-US and the "My Profile", "Edit my profile", "Edit settings", "Manage watch list" section is in the right part but in Kasey's print screen is in the left.
@kkellydesign This is not merged?
Here is a print screen with my result: 
![Screenshot 2020-02-04 at 17 40 39](https://user-images.githubusercontent.com/54845678/73760418-f5df0180-4775-11ea-8b48-b0301a748698.png)

**Comment by kkellydesign** [comment] 2020-02-04 17:09
@ovidiuboca1 Making all of the sidebars site-wide on the left was a recent change request by @jess-cook03 – what you have here is correct.

**Comment by ovidiuboca1** [comment] 2020-02-05 07:51
Thanks for clearing this out. 
@kkellydesign the "Heads up!" warning doesn't have a close button and also if I select "Edit settings" or "Manage watch list" options the warning disappears, this is intended? Please let me know if I need to log a separate bug for this.

**Comment by kkellydesign** [comment] 2020-02-11 14:53
The close button here is fixed. 

As far as the pages that this lives on, this is the intended behavior. It's my understanding that those pages are still going to exist when the FFA accounts are fully implemented, because they're site-specific. I think this one is safe to close out.

**Comment by ovidiuboca1** [comment] 2020-02-11 15:15
This was verified on https://test.sumo.mozit.cloud/en-US/ and everything works as expected.

**Closed** 2020-04-14 17:38 UTC
Labels: bug
