### ISSUE TITLE
Responsive Redesign // Establish new "card" patterns

### ISSUE THREAD

**Issue by kkellydesign** [mozilla/sumo-project#61] opened 2019-11-04 17:57 UTC
These new patterns are used throughout the system and may contain a border or drop-shadow. @jess-cook03 if there are new designs for any of these patterns, please include zeplin links on this card. Otherwise, I'll set the existing designs in stone in the styleguide.

Examples of card variations:

- [x] Topics list: https://support.mozilla.org/en-US/
- [x] Frequent Topics list: https://support.mozilla.org/en-US/products/firefox
- [x] Callouts ("Ask the Community"): https://support.mozilla.org/en-US/products/firefox
- [x] Well ("Was this article helpful?") https://support.mozilla.org/en-US/kb/get-community-support
- [x] feature content (large box) https://support.mozilla.org/en-US/users/auth

@madasan please assign me and @jess-cook03, and add this ticket to the backlog.

**Comment by jess-cook03** [comment] 2020-01-13 18:10
@kkellydesign for the cards ... could we add a hover state? One that elevates the card a bit in addition to the title getting the underline?
See mozilla.org -- they had a stroke on hover.
<img width="469" alt="Screen Shot 2020-01-13 at 12 07 09 PM" src="https://user-images.githubusercontent.com/54991698/72280275-9752b780-35fd-11ea-98e6-27f44c4b8ad2.png">
Wondering if we keep the shadow and then just adding in the stroke?

**Comment by kkellydesign** [comment] 2020-01-23 18:11
@jess-cook03 This will be in the next PR this afternoon. I took this straight from the mozilla.org code, but I think this conflicts a bit when we use it in combination with the drop shadow. It's a bit too subtle here (the one on the right is the hovered state). It uses the same 'border-color' variable that I use everywhere else in the system, which is 'marketing grey 2'. But I could go darker for this if you want. 
 
<img width="694" alt="Screen Shot 2020-01-23 at 1 01 42 PM" src="https://user-images.githubusercontent.com/202590/73011147-abf33480-3de1-11ea-82e7-85feda05fa88.png">

**Comment by jess-cook03** [comment] 2020-01-23 18:51
@kkellydesign hmmm agree that this does not work very well at all, considering the cards shadow... I'm wondering if it would be possible to play around with some different, new hover options for these cards.
I pulled some references here:
Maybe slight enlargement of size when hovering? Something like this?
![hover_enlarge](https://user-images.githubusercontent.com/54991698/73013906-37bb8f80-3de7-11ea-8586-6351146d07ea.gif)
![hover-action_enlarge size](https://user-images.githubusercontent.com/54991698/73013910-37bb8f80-3de7-11ea-8d12-7dfeb82f7680.gif)
Or maybe a shadow transition? Something like these? But with this one I feel like the card deafult shadows would then need to be tweaked a bit globally.
![shadowTransitions](https://user-images.githubusercontent.com/54991698/73014038-72bdc300-3de7-11ea-9650-ac90eee84ef4.gif)
![shadow transition](https://user-images.githubusercontent.com/54991698/73014041-75201d00-3de7-11ea-9c4c-76c28e1981ce.jpg)

**Comment by kkellydesign** [comment] 2020-01-23 19:27
The recording is a little choppy because it's a gif, but this will give you an idea. 

![Screen Recording 2020-01-23 at 2 18 08 PM](https://user-images.githubusercontent.com/202590/73016729-6b4ce880-3dec-11ea-98a0-36315f60d7cf.gif)

**Comment by ovidiuboca1** [comment] 2020-01-28 12:40
I tested this on https://test.sumo.mozit.cloud/en-US/ and I found out that there are different behaviors on various browsers. On Firefox everything works as expected, see Kasey's gif. If you use Chrome or Safari browsers the behavior changes if you hover over the products section or feature articles, the font of the text becomes blurry. Screen recording with the actual results: https://streamable.com/si3fp

**Comment by kkellydesign** [comment] 2020-01-29 21:20
This has been improved by adding hardware acceleration and some specific font anti-aliasing to the hover property. This will be in https://github.com/mozilla/kitsune/pull/4150.


![Screen Recording 2020-01-29 at 4 15 14 PM](https://user-images.githubusercontent.com/202590/73398323-3db3e380-42b3-11ea-8d98-06cdbed4492b.gif)

**Comment by kkellydesign** [comment] 2020-02-11 14:56
This is in and can be tested in Chrome here: https://test.sumo.mozit.cloud/en-US/

**Comment by ovidiuboca1** [comment] 2020-02-11 15:20
Tested on https://test.sumo.mozit.cloud/en-US/ and the issue is still there, I"m on Mac OS 10.14 with Chrome v.80. There are some prerequisites that need to be done?

**Comment by kkellydesign** [comment] 2020-02-19 21:42
I added one more line that might help out in chrome, but a little blurriness might be unavoidable in some screen resolutions because we're telling the browser to zoom in on fonts. It looks good in Firefox, so I think this is acceptable. If not, we may need to revisit the hover states to something that doesn't use zoom.

**Comment by ovidiuboca1** [comment] 2020-02-20 08:24
I've just tested it and in my opinion, there is a visible difference between Firefox and Chrome, I don't know how hard is to fix this and like you said on FF looks good.

**Comment by jess-cook03** [comment] 2020-02-21 13:47
@kkellydesign @ovidiuboca1 
Re zooming:
I have been looking at this and comparing the two browsers and honestly its so slight of a blur that I'm not sure how big of an issue it is.
My only concern would be if the blurriness causes accessibility issues? But then again it's not even that bad, in my opinion.

@kkellydesign That being said what zoom did we land on? .5 ? and if its not .5 can it be? 
I don't want to sacrifice the zooming effect -- I think it enhances the card experience a lot -- if anything I would rather look into how we can get this effect without it using zoom if its an issue. Goal is having the cards enlarge a little on hover to bring emphasis

**Comment by ovidiuboca1** [comment] 2020-02-24 09:49
Like jess mentioned, I think we need to decide how big of an issue it is and if this needs to be fixed now.

**Comment by jess-cook03** [comment] 2020-02-24 16:36
@madasan @akatsoulas 
As I mentioned -- I think this is fine for now but would like you both to give this the final okay?
Moving to blocked until then.

**Comment by akatsoulas** [comment] 2020-02-27 16:25
I believe the current behavior is acceptable

**Comment by madasan** [comment] 2020-02-27 16:30
This is works for me

**Comment by jess-cook03** [comment] 2020-03-10 19:37
This is completed -- @madasan maybe we want to backlog this for the interaction if we want to improve it in the future

**Closed** 2020-04-15 07:01 UTC
