### ISSUE TITLE
Not seeing 'Helpful?' voting UI on forum pages 

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo-project#210] opened 2020-03-05 18:48 UTC
@kkellydesign @ovidiuboca1 please feel free to add more details to this!
I think there is some confusion about this but I'm not seeing this either on the forum pages, unless I'm doing something wrong?

But this is what it should look like for reference:
<img width="755" alt="Screen Shot 2020-03-05 at 11 27 01 AM" src="https://user-images.githubusercontent.com/54991698/76014591-e32c2980-5ee7-11ea-9ee7-9a397e3a3799.png">

**Comment by ovidiuboca1** [comment] 2020-03-06 07:52
Visit this URL: https://test.sumo.mozit.cloud/en-US/kb/troubleshoot-SEC_ERROR_UNKNOWN_ISSUER
Look at the voting UI, this is different from the expected result. Here is my result: 
![Screenshot 2020-03-06 at 09 20 08](https://user-images.githubusercontent.com/54845678/76063291-1d510600-5f90-11ea-8722-1c312635fe9f.png)

Tested on Firefox on Mac OS X 10.14.

**Comment by kkellydesign** [comment] 2020-03-06 18:35
@ovidiuboca1 The URL you've provided is a document page. The iam_test user account has already answered the survey for that article, so you can't see the form. If you log out or look at that URL on private browsing, the sidebar form will show up again. 

The 'Helpful?' form that @jess-cook03 is mentioning is attached to answer replies in the forums. That form has two conditionals around it: 
```
{% if answer.id and question.editable %}
{% if user != answer.creator %}
```
This means it won't appear if the question (page-level) has been archived, or if the logged-in user is also the author of the response that you're trying to vote on (as in, you can't upvote yourself).  My guess is that we're having a hard time finding these forms to test on the testing server because we're all using the same account, and many of the articles on the testing server have been archived. 

For example, this one has responses from non-JOHN user accounts, but it's been archived (which you can see with the blue banner at the top of the page): 
https://test.sumo.mozit.cloud/en-US/questions/1197931

As I'm going through the test server, all of the articles I'm seeing are archived.

SO! In order to test this, we need one of two things, and @akatsoulas will need to help with either, because our testing account doesn't get us into /admin on the test server: 

1) We need a handful of articles to be un-archived so this form shows up on answers that aren't attached to the JOHN/iam_test user account. That way, the test account can upvote and downvote those answers. 
2) We need an additional testing account so that we can ask a question, answer it with the other account, and then log in with the first account in order to upvote the answer. 

I'm moving this to blocked and adding the BE tag, since we need a little more help to sort this out.

**Comment by kkellydesign** [comment] 2020-03-06 18:44
I can confirm that the above tactics work to enable this functionality. I just ran through it all on my local instance. Here are several states: 

<img width="342" alt="Screen Shot 2020-03-06 at 1 42 56 PM" src="https://user-images.githubusercontent.com/202590/76112625-85174900-5fb0-11ea-9712-5d18a4c288af.png">

<img width="964" alt="Screen Shot 2020-03-06 at 1 42 03 PM" src="https://user-images.githubusercontent.com/202590/76112617-834d8580-5fb0-11ea-9cde-fc23589fe80e.png">
<img width="356" alt="Screen Shot 2020-03-06 at 1 42 23 PM" src="https://user-images.githubusercontent.com/202590/76112623-847eb280-5fb0-11ea-87a2-db26d6d4f744.png">
<img width="339" alt="Screen Shot 2020-03-06 at 1 42 42 PM" src="https://user-images.githubusercontent.com/202590/76112624-85174900-5fb0-11ea-82d5-6cacca4cb9f8.png">

**Comment by akatsoulas** [comment] 2020-03-13 15:22
I believe this is solved. @ovidiuboca1 can you confirm?

**Comment by akatsoulas** [comment] 2020-03-13 15:23
Upon re-reading this, let's keep it in the QA column and test it in the staging instance.

**Comment by ovidiuboca1** [comment] 2020-03-16 05:50
I confirm the behavior " The URL you've provided is a document page. The iam_test user account has already answered the survey for that article, so you can't see the form. If you log out or look at that URL on private browsing, the sidebar form will show up again"

**Comment by ovidiuboca1** [comment] 2020-03-17 07:04
@jess-cook03 can you please take a look and if you consider this done please move it under ready to deploy.

**Comment by jess-cook03** [comment] 2020-03-17 15:26
@ovidiuboca1 I am having trouble testing this myself --- since you have already confirmed above that this behavior is indeed correct, I am going to move it based on that. Thanks!

**Closed** 2020-04-15 07:11 UTC
Labels: BE attention needed
