### ISSUE TITLE
Allow users to edit their username.

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo-project#580] opened 2020-08-26 14:58 UTC

**Comment by mirunacurtean** [comment] 2020-08-27 13:36
@jess-cook03  Could you please check if the current behavior in stage is as expected or if any other improvements are needed? 

Username and display name are different fields due to the latest change. 
Updating the username on sumo UI also updates on in admin side. 
If a display name is not added and saved then the username will show on the left side of the avatar icon. 
Both username and Display name fields are editable by the user. 
The username field can only be updated but not left blank; trying to update the profile without adding anything in the Username field border will be highlighted as warning in red and when trying to save the changes by pressing the "Update my profile" button will redirect to the field with the indication to "Please fill out this field" (tool-tip positioning could be improved)
![Username field required](https://user-images.githubusercontent.com/53306802/91448832-0d511980-e883-11ea-81fa-1fc07e082d89.gif)


Creating a new SUMO account based on a FxA account that has a display name will result in a SUMO account with the same display name. Erasing or updating the FxA account display name will not change the SUMO account display name. 
![Fxa username and display name are correctly added to SUMO account fields upon account creation](https://user-images.githubusercontent.com/53306802/91447930-e9d99f00-e881-11ea-910a-e2b165ced3bd.gif)


Other contributors that have access to Community hub can search for the user's account by either username or display name and can see both on user's profile.
![user can be found using username and display name](https://user-images.githubusercontent.com/53306802/91447883-db8b8300-e881-11ea-88bd-de791aed249d.gif)


In terms of updating the username in accordance with the username help text is done successfully only when using numbers, letters and the allowed symbols. (@,+,- and _ ).
Using any other symbol results in a 500 internal error or a warning underlining the rules. 
No more than 150 characters can be inputted into the field.
![An error occured when trying to modify username](https://user-images.githubusercontent.com/53306802/91447970-fb22ab80-e881-11ea-91df-f8d53b82612c.gif)

![Character number test](https://user-images.githubusercontent.com/53306802/91447981-ff4ec900-e881-11ea-9f0d-c6a9be7af92c.gif)

@akatsoulas  Could something be done about the error situation so that when trying to save a username that contains an unapproved symbol so that it defaults the same behavior as when trying to leave the username field blank?

**Comment by jess-cook03** [comment] 2020-08-27 20:49
@akatsoulas @LeoMcA 
With this we need to make some changes to the 'my profile' page too
![ProfilePages_MyProfile_Desktop_01](https://user-images.githubusercontent.com/54991698/91493347-2eb30500-e885-11ea-9e7e-f949a616d65a.png)

**Comment by jess-cook03** [comment] 2020-08-27 20:57
As for the 'edit page':
![ProfilePages_Edit_Desktop_02](https://user-images.githubusercontent.com/54991698/91494126-5f476e80-e886-11ea-8a8b-747c293c1181.png)

**Comment by jess-cook03** [comment] 2020-08-27 21:02
@akatsoulas @mirunacurtean @LeoMcA 
In regards to the error state re:

> The username field can only be updated but not left blank; trying to update the profile without adding anything in the Username field border will be highlighted as warning in red and when trying to save the changes by pressing the "Update my profile" button will redirect to the field with the indication to "Please fill out this field" (tool-tip positioning could be improved)
Username field required

The field should stay highlighted red when left empty or if error occurs the whole time. Meaning after hitting the 'update' button the tooltip should appear as shown, but it should properly anchor to the effected field #1 and then #2 the field should remain highlighted red as well.

Is this possible?

Right now in the video, it shows that after you click the 'update' button the page looks as if it refreshes, catches the error, but it doesn't properly locate it or show any red highlight indication anymore.

**Comment by jess-cook03** [comment] 2020-08-27 21:05
Also side note --- the initial welcome message green alert banner component should appear at the top of page, not below the search when the user first signs in after account creation.
I can file a separate bug for that.

**Comment by akatsoulas** [comment] 2020-08-31 13:09
The 500 error is a bug and not a way to handle improper input in the field. I am looking into it.

I will work on updating the error fields and tooltips and squash as many as Jess's suggestions as possible. Please keep in mind that the username has some strong requirements that are hard to change or the benefit of doing so won't be greater than the effort needed to overhaul the back-end mechanics here. I am mostly referring to the max_length and the accepted characters.

Although the username and the display name overlap, we agreed for now to start with the username by making it editable and then have multiple iterations to tackle many UI options in the profile and to also figure out what we are going to do with the display name once the users have the ability to edit the username. 

I will update this ticket when I have a PR which fixes the bugs and handles the form errors better.

**Comment by akatsoulas** [comment] 2020-08-31 13:10
> Also side note --- the initial welcome message green alert banner component should appear at the top of page, not below the search when the user first signs in after account creation.
> I can file a separate bug for that.

That would be great! There is also issue #31 which we can use to track all the sub-issues related to the profile pages and input fields.

**Comment by akatsoulas** [comment] 2020-08-31 15:53
Something to notice regarding the avatar - users cannot change the avatar through sumo. They need to update it through their profile in Firefox Accounts.

**Comment by jess-cook03** [comment] 2020-08-31 16:39
Thank you! @akatsoulas That is really great info to note about the avatar .... I did not know that .... that will change the UI a bit (order of info) on the edit page. Thank you for pointing this out!

> Please keep in mind that the username has some strong requirements that are hard to change or the benefit of doing so won't be greater than the effort needed to overhaul the back-end mechanics here. I am mostly referring to the max_length and the accepted characters.

☝️this is totally fine, I hear you. Whatever the requirements we need to have for this are fine, lets just make sure the copy underneath is relevant and updated to reflect them. So do let me know if we need to refine the copy?

 

> ...figure out what we are going to do with the display name once the users have the ability to edit the username.

My hunch here is we will move away from the display name concept altogether.... we can think and discuss more about it. But that was the initial UX proposal for changes a while back. TBD 👍

**Comment by akatsoulas** [comment] 2020-08-31 19:03
I opened a PR here https://github.com/mozilla/kitsune/pull/4518 which should tackle all the comments above

**Comment by mirunacurtean** [comment] 2020-09-03 14:20
**My profile page** - UI changes and header size- they look to be in accordance with the request.
![My profile UI changes](https://user-images.githubusercontent.com/53306802/92125931-43087c00-ee08-11ea-8253-06735a66f5fe.jpg)
**Note 1** -clicking on the "click here" hyperlink results in a 404 request.  

![404 not found](https://user-images.githubusercontent.com/53306802/92125963-4996f380-ee08-11ea-8caf-d683f60ad9d3.gif)


**Edit profile** - UI changes look as expected (added label, star indicator, header size and 'Your account' title and help text updated)
Copy changes - in accordance with the PR and as requested 
![edit profile UI changes](https://user-images.githubusercontent.com/53306802/92126054-64696800-ee08-11ea-836a-7c8afd386e58.jpg)

Upload button has not been added due to the user's ability to change avatar from FxA profile only. https://github.com/mozilla/sumo-project/issues/580#issuecomment-683866247
The requested buttons and "close account.." link have been aligned to the right as requested. 
Cannot write in or copy more than 150 characters in the username field and if trying to save a symvbol that's not accepted the "Enter a valid username. This value may contain only letters, numbers, and @/./+/-/_ characters." warning message will show. 
**Note 2** -  could update the "and @/./+/-/_ characters" part of the message as well to "Letters, digits and @.+-_ only. " - should we leave it off as a new ticket or part of a still open Responsive redesign one? 
**Note 3** - When trying to update the profile after erasing the username the jump to the required field is not made properly and the tooltip is not attached to that field when scrolling (see GIF below).  - Should I add another ticket for it? 
**Note 4** -  The right top of the page avatar has been compressed to less than half it's initial size and shape. 

![warning message and tooltip](https://user-images.githubusercontent.com/53306802/92126793-494b2800-ee09-11ea-9c4b-adfa6e57f37b.gif)

@akatsoulas  I've confirmed the expected behaviors. Please see the Notes for new and known issues that could be improved.

**Comment by mirunacurtean** [comment] 2020-09-04 14:50
I've created a new issue for all the notes to be resolved in (https://github.com/mozilla/sumo-project/issues/586) and, with the specification that the avatar issues should be fixed if it's a regression caused by changes made for this issue, this ticket can be released as is.

**Comment by akatsoulas** [comment] 2020-09-07 12:52
Moving this to ready to deploy since all the remaining issues/notes are tracked in #586

**Comment by jess-cook03** [comment] 2020-09-11 17:18
@LeoMcA @akatsoulas 
I do have to follow up with a few notes here, after taking a deeper look, some of these changes may block the release Monday -- lets discuss if that is true.

Between tickets #586 and this ticket as well as #587 ....

- [ ] For the avatar -- since the avatar image can only be changed via FxA settings... would it be possible to re-order the information a bit and relocate the avatar image closer to the fxa section?.... see image below. 
This can be broken out and make a separate ticket if it can't be achieved with this update, just let me know.
<img width="1440" alt="ProfilePages_MyProfile_Desktop_Revised01" src="https://user-images.githubusercontent.com/54991698/92952844-a7da5c80-f42e-11ea-951f-3033402f2eb5.png">


- [ ] The asterisk star * attached to the username field -- can we make this default to our alert red color (same as error)instead of the text color? 

- [ ] On my profile page - very minor editorial change -- "Your privacy is important to us, your username is always visible to the public, if you would like to edit your username click here." <<< add the period punctuation to the end of the sentence (.) 

- [ ] Check box 'make my email public' --- looking for some clarity here -- this makes your email address public on your sumo  profile if other users look you up, etc. correct? That being said I think the language and placement needs tweaking - see images below. Copy suggested change to 'make my email address public' instead..... placement could be moved around.... its more of a settings rather than a 'edit your profile' field... so I would suggest moving it completely to 'edit settings' page - see below. 
<img width="1440" alt="ProfilePages_Edit_Desktop_Revised02" src="https://user-images.githubusercontent.com/54991698/92954217-14565b00-f431-11ea-8838-1d04e8ed5f38.png">
<img width="1440" alt="Edit Settings_" src="https://user-images.githubusercontent.com/54991698/92954225-17514b80-f431-11ea-8b1e-d1f6ff56be8d.png">

If this needs more discussion lets review together on Monday!!

**Comment by LeoMcA** [comment] 2020-09-11 21:36
https://github.com/mozilla/kitsune/pull/4528 fixes most of the above, one thing will require a bit more consideration:

> this makes your email address public on your sumo profile if other users look you up, etc. correct?

It seems to only make your email address visible to logged in users.

> Copy suggested change to 'Make my email address public' or 'Allow my email address to be visible to the public' instead..... 

I made it "Make my email address visible to logged in users" to reflect the above.

> placement could be moved around.... its more of a settings rather than a 'edit your profile' field... so I would suggest moving it completely to 'edit settings' page - see below.

Currently the options presented in "Edit Profile" and those presented in "Edit Settings" are stored differently in DB, so moving it would require some kind of rearchitecting on the back end.

**Comment by LeoMcA** [comment] 2020-09-14 12:34
https://github.com/mozilla/kitsune/pull/4528 is deployed on staging

**Comment by jess-cook03** [comment] 2020-09-14 14:27
@LeoMcA 
Taking a look at staging right now.

Looking good thus far. 
Email address checkbox is fine for now -- I think we should circle back to evaluate and discuss if we really need this? I'd like to understand better what value this is (or is not) bringing to our users?

I did notice in the page templates between the 'my profile' and 'edit profile' pages there is some spacing differences in the header area... they should be the same. Take a look below. There is some jumping back and forth of content when tabbing between these pages.

**The correct spacing is on the "my profile" page**

The Your Account and email address and FxA info should be spaced the same on both pages the edit page looks too spaced out.

![Screen Shot 2020-09-10 at 2 05 46 PM](https://user-images.githubusercontent.com/54991698/93097392-83bb8d00-f673-11ea-86bb-bde5470aa285.png)
![Screen Shot 2020-09-10 at 2 05 33 PM](https://user-images.githubusercontent.com/54991698/93097414-8918d780-f673-11ea-8324-3ae8f8e80c3c.png)

<img width="1328" alt="Screen Shot 2020-09-14 at 9 59 23 AM" src="https://user-images.githubusercontent.com/54991698/93098010-53282300-f674-11ea-8bdb-890592b3d43b.png">

After these changes - I would say this is good to go from my end.
Thank you!

**Comment by LeoMcA** [comment] 2020-09-15 12:02
Nice! Those changes have been deployed on staging.

**Comment by mirunacurtean** [comment] 2020-09-21 13:37
Looked over the UI changes and they look good to me too. 

As for other test results, they are listed here:
Edit username test cases
1. Add duplicate username from edit profile page:
- add duplicate > hit enter  > user receives duplicate warning message, the username is not updated

- add duplicate> update profile > see warning message > refresh page > username field value does not return to actual value. 
- add duplicate> update profile > see warning message > select Cancel button  >  username field value does not return to actual value. 

This was the functionality from the start in these two last flows but it would have  looked better for the end result (even when using Cancel) to be a page refresh that removes the duplicate username and warning and shows the actual username in that field.  
![refresh and cancel](https://user-images.githubusercontent.com/53306802/93771533-5009d580-fc26-11ea-9766-f9046bb709a8.gif)

@jess-cook03 Could you please provide your input as well on the two examples above? @akatsoulas Should I add a different issue for them?

- add duplicate> update profile > see warning message > Sign up and Sign in
(make sure that previous username is still the one used in Username field) > 
duplicate username is removed and the profile field is populated with the existing valid username.

- add duplicate> update profile > see warning message > switch to a different page and then return to edit profile > duplicate username is removed and the profile field is populated with the existing valid username.


2. Create new account with a username that already exists.
Mozilla accounts:
- Creating a new account directly on SUMO means using a new email account and the username is automatically derived from that - could not create an account with a duplicate username that way,
- Create a new sumo profile using an existing FXA account - the fxa username is based on the email it was created on so it was unlikely to create a duplicate profile usrname unless there are mozilla emails created using the exact same name. 
Note. Updating the Display name in fxa manage account page results in creating a sumo profile display name and does nothing to alter the username. The sumo username is still derived fom the fxa account email. 

Other email accounts-  mailinator account test.
- I've created a simple mozilla test account profile and have used the same username in creating a mailinator based account. 
The username of the mozilla account is, by default, assigned a system generated number as part of the username.
The mailinator account username, when the account is created, (as seen in the sumo profile page) is automatically assigned a different number thus preventing the creation of duplicates. 
![same email name but different username](https://user-images.githubusercontent.com/53306802/93773147-66b12c00-fc28-11ea-9ff3-81be6a4116d5.gif)


3.  Adding a username that was used in a now deleted SUMO account. This can be done successfully right after the sumo account is closed and its profile info is deleted.

Other than the Cancel and refresh issues this is working as expected.

**Comment by akatsoulas** [comment] 2020-09-21 15:10
@mirunacurtean regarding the scenario where you post a duplicate username -> get the error -> refresh page, the reason it does not revert to the initial username is because by refreshing you are re-posting the request with the duplicate username and the server responds again with an error. If you replace the post with a get request, by clicking enter on the url for example, the username is restored to the original value. Is this the case?

Regarding the cancel button, I am looking into it.

**Comment by jess-cook03** [comment] 2020-09-21 17:46
@mirunacurtean and @akatsoulas I am doing my best to follow and understand what we are suggesting/questioning here.

I agree that the expected behavior for:

> add duplicate> update profile > see warning message > refresh page > username field value does not return to actual value.

Should be as Tasos stated above -- _"because by refreshing you are re-posting the request with the duplicate username and the server responds again with an error."_ 
^^^ This makes sense to me and would likely be expected from users as well. I would not expect that after submitting and seeing a error that refreshing the page would clear the error, instead refreshing would and should still show the error as I believe Tasos is describing.

... I would imagine for users to clear or fix the error they need to change the field manually themselves by entering something different OR by hitting the cancel button.... hitting cancel I would expect the fields to return to their previous state before engaging the edit interaction.

I think also what could help the UX in these error situations would be addressing  #587 to where the alert/error anchor message appears (similar to the 'please fill this field' required message that we have) or adding this in as a new functionality to error messaging that includes some type of messaging that is not in-line, but supports it.
Could be this anchor solution or could be alert message at the top of the page..... I digress this would be its own separate ticket/issue I imagine ? We should discuss.


I think out of the 3 situations above the cancel button is the only one sticking out to me that should have the suggested end result @mirunacurtean mentioned: 
> This was the functionality from the start in these two last flows but it would have looked better for the end result (even when using Cancel) to be a page refresh that removes the duplicate username and warning and shows the actual username in that field.

Hope this helps.... please ping me with questions or we can discuss tomorrow in our checkin!!!

**Comment by mirunacurtean** [comment] 2020-09-24 07:20
@akatsoulas @LeoMcA Note that I've logged a profile related issue https://github.com/mozilla/sumo-project/issues/634

**Closed** 2020-09-24 13:41 UTC
Labels: kitsune
