### ISSUE TITLE
On mobile left side of translation preview is cut off

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/sumo-project#365] opened 2020-04-16 11:46 UTC
From https://github.com/mozilla/sumo-project/issues/346#issuecomment-614586225:

When previewing a translation on mobile the left side of the preview is cut off:

![Screen Shot 2020-04-16 at 12 45 14](https://user-images.githubusercontent.com/755354/79452483-221dc680-7fe0-11ea-8472-0fda802acbe2.png)

e.g. https://support.allizom.org/ro/kb/change-your-default-search-settings-firefox/translate?discard=%C3%8Enl%C4%83tur%C4%83#preview

**Comment by kkellydesign** [comment] 2020-04-16 13:47
This is fixed – duplicate of this issue: https://github.com/mozilla/sumo-project/issues/366#issuecomment-614661969

**Comment by ovidiuboca1** [comment] 2020-04-17 10:05
This was verified, see issue #366.

**Closed** 2020-04-20 15:36 UTC
Labels: bug
