### ISSUE TITLE
0 search results are shown when using a new keyword after the previous search request results have been filtered by product 

### ISSUE THREAD

**Issue by mirunacurtean** [mozilla/sumo-project#714] opened 2020-12-17 07:18 UTC
**Steps to reproduce:**
1. Enter a test search keyword in the search bar on https://support.allizom.org/en-US/. For example "keyword" 
2.  Filter the results by product. "Firefox Focus" is a safe bet in this instance. 
3. Remove the search keyword and add a new one that is also expected to have results. 
4. View results. 

**Actual results:**
0 search results are found and filtering by product to another category that might have a response is no longer possible. 
![0 search results when updating keyword](https://user-images.githubusercontent.com/53306802/102455684-af6e5a80-4048-11eb-9ae2-306fc46707aa.gif)

**Expected results:** 
When page is refreshed and the search is performed again using the second keyword, Filter by product list, with the previously selected product category search along with the results, are listed. This should work instantly without needing to refresh the page.

**Comment by akatsoulas** [comment] 2021-02-11 17:03
Should be similar or duplicate of #169

**Comment by mirunacurtean** [comment] 2021-02-23 17:33
Verified fixed - Search for "keyword" lists results and filtering by product updates those results. If there are no results the specific message is shown and the "Filter by product" section is still displayed and functional. Selecting another product will update the search results as well.
![image](https://user-images.githubusercontent.com/53306802/108882544-2dcd1700-760d-11eb-9e92-b5b8b2596e81.png)


Both when there are search results or when there are 0 on a filtered product after which the search filed is cleared and another search keyword/phrase is used, the search results will be updated to reflect that change for the product category selected in the previous search round. 
![image](https://user-images.githubusercontent.com/53306802/108883004-99af7f80-760d-11eb-8584-9736c85e9f22.png)

Switching to another product category is possible and the search results will be relevant to the latest search keyword/phrase. 
![image](https://user-images.githubusercontent.com/53306802/108883119-bd72c580-760d-11eb-925d-c8c935296a18.png)

**Closed** 2021-03-16 14:45 UTC
Labels: bug
