### ISSUE TITLE
Update username algo to handle IntegrityError

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/sumo-project#633] opened 2020-09-22 15:35 UTC

**Comment by LeoMcA** [comment] 2020-09-24 09:51
The issue was with "+"s in emails, where they were duplicated. But I'm now able to log in with leomcardle+5@ and the username gets automatically changed to "leomcardle+51"

**Comment by mirunacurtean** [comment] 2020-09-24 12:31
Confirmed as fixed as well. Created username mcurtean+85 and then signed up with the email mcurtean+85@mozilla.com which was automatically assigned mcurtean+851 as a username. 
![+ verified fixed](https://user-images.githubusercontent.com/53306802/94144770-3cef4380-fe7a-11ea-86df-7c7ab23db055.gif)

Due to other test cases in which the email address contains "-", or "." instead of a "+" sign not being valid (no verification email is sent when trying to create such an account), I'm marking this as Ready for Release.

**Closed** 2020-09-24 13:40 UTC
Labels: bug, kitsune
