### ISSUE TITLE
Move thread button in forus doesn't work.

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo-project#318] opened 2020-04-01 15:14 UTC
on bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1630198

**Comment by kkellydesign** [comment] 2020-04-15 20:39
This is fixed – the submit button was outside of the <form> element. 

https://github.com/mozilla/kitsune/pull/4312

**Comment by ovidiuboca1** [comment] 2020-04-16 09:41
I tested on desktop, Mac OS X 10.14, Windows 10 with FF and chrome and I can confirm the fix.
Also, tested on mobile and the issue is fixed.

**Comment by kelimuttu** [comment] 2020-04-16 13:29
In addition to that, I do think that the button need some more padding on the bottom. It looks too close to the next sidebar heading. 

![Screenshot_2020-04-16 adjusting tab sync across devices SUMO community discussions Forums Mozilla Support](https://user-images.githubusercontent.com/4922388/79461746-c6276200-8020-11ea-99d4-1949a88ef27c.png)

**Comment by kkellydesign** [comment] 2020-04-16 14:01
@kelimuttu That should be fixed as well when this fix is deployed. This is what I'm seeing currently from my fix yesterday, but it's not yet deployed: 

<img width="350" alt="Screen Shot 2020-04-16 at 9 57 35 AM" src="https://user-images.githubusercontent.com/202590/79465165-fb07ca80-7fc8-11ea-8fca-ac61740795da.png">

**Comment by kelimuttu** [comment] 2020-04-16 14:40
That's cool. Thank you for the swift fix @kkellydesign

**Closed** 2020-04-20 15:39 UTC
Labels: bug
