### ISSUE TITLE
[Search] The search can't be performed from the search bar

### ISSUE THREAD

**Issue by ovidiuboca1** [mozilla/sumo-project#167] opened 2020-02-17 13:05 UTC
STR:

1. Go to https://test.sumo.mozit.cloud/en-US/
2. Scroll down until the search bar from the stickie header is displayed. 
3. Enter a word and perform a search, I used "firefox"

ER: The search is performed and the results are displayed. 
AR: You can't enter the word because the search bar disappears. 
NOTE: The issue is similar to mobile/tablet devices

Here is a screen recording with the actual result - https://streamable.com/4efsw

**Comment by kkellydesign** [comment] 2020-02-19 21:08
This will be fixed in https://github.com/mozilla/kitsune/pull/4182

**Comment by kkellydesign** [comment] 2020-02-20 14:03
ready to test: https://test.sumo.mozit.cloud/en-US/

**Comment by ovidiuboca1** [comment] 2020-02-20 15:12
I tested on the iPad and the issue is still there. 
On the iPhone, after I scroll the page and click on the magnifying glass icon nothing happens.

**Comment by kkellydesign** [comment] 2020-02-25 22:20
Please try this again – I think this is working as intended. As soon as you start typing, the toolbar does disappear because we jump you to the top of the screen to show the results. We're also grabbing the characters that you've started typing and moved the focus to the main search field in the page masthead. It's all a bit weird because we hijack the entire page layout, but functionally it works. If you're still having issues on iphone or ipad, please do a screen recording so I can see what's going on. I just tested on mine though, and it looks good.

**Comment by ovidiuboca1** [comment] 2020-02-26 12:52
@kkellydesign I tested on desktop and the issue seems to be fixed, the problem is still there on mobile devices. If I scroll the page and click on the magnifying glass icon nothing happens. Please let me know if you can see the issue.

**Comment by kkellydesign** [comment] 2020-02-26 13:44
The button acts as 'submit' to the field, so clicking on that while the field is blank doesn't fire any actions. If you click on the field and start typing, it should all work as expected. 

This seems to be the expected behavior to me, but we can discuss adding some additional javascript that focuses the text field if you'd like.

**Comment by ovidiuboca1** [comment] 2020-02-27 14:57
On mobile, if you click on the magnifying glass from the sticky bar nothing happens, the search can be performed, the user can't enter any inputs.

**Closed** 2020-04-15 07:10 UTC
Labels: bug
