### ISSUE TITLE
[desktop] UI issues on HomePage

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/sumo-project#125] opened 2020-01-17 09:57 UTC
1. Product logos should be displayed in the left side of the text, instead of above the text (as per [designs](https://app.zeplin.io/project/5db3524d3cd0612c5d2f78a9/screen/5dd873054a74858ba790640d))

![Screenshot_2020-01-17 Mozilla Support](https://user-images.githubusercontent.com/5293100/72602393-de9fb780-391f-11ea-9588-27152f86bc93.png)

2. Sections titles should be left aligned, instead of centered
![Screenshot_2020-01-17 Mozilla Support(1)](https://user-images.githubusercontent.com/5293100/72602684-52da5b00-3920-11ea-809b-3e5df3921dd8.png)

CC @jess-cook03

**Comment by jess-cook03** [comment] 2020-01-17 21:06
@viorelaioia thank you for this -- you are correct, we have shifted the designs to be left aligned and the product logos should look like the webmaker card with logos sitting left aligned as well.

CC @kkellydesign

**Comment by kkellydesign** [comment] 2020-01-17 23:33
Duplicate of this, finished. https://github.com/mozilla/sumo-project/issues/26

**Comment by ovidiuboca1** [comment] 2020-01-27 08:35
Tested on the test environment https://test.sumo.mozit.cloud/en-US/ and the issue is fixed.

**Closed** 2020-04-14 17:39 UTC
Labels: bug
