### ISSUE TITLE
The user is logged out after some time

### ISSUE THREAD

**Issue by ovidiuboca1** [mozilla/sumo-project#416] opened 2020-05-05 15:10 UTC
CC @akatsoulas, @LeoMcA 

Prerequisites: 
Use the staging site - support.allizom.org

STR:

1. Go to support.allizom.org
2. Log in 
3. Start to navigate on the site (Click on the products, click around for a couple of minutes)

ER: Everything works as expected and the user is still logged in at the end of the session. 

AR: After a couple of minutes the user is logged out and if he/she attempts to log back in an error is displayed "This account is not active". In my case after ~ 5 sec, I was logged out
Here is a screen recording - https://streamable.com/zsawwm

NOTE:  We were able to reproduce this with Firefox 75 and Chrome on Mac OS X 10.14 and Windows 10 using the staging site, on production the issue is not reproducible.

**Comment by mirunacurtean** [comment] 2020-05-20 13:47
Still occurs in stage when logging in with existing accounts. The account is logged out when trying save modifications made to an article. 
Tested on Windows pro 10 64-bit and Mac OS X 10.14 on FF and chrome browsers.

**Comment by akatsoulas** [comment] 2020-05-22 11:02
Duplicate of #415

**Closed by akatsoulas** 2020-05-22 11:02 UTC
Labels: bug
