### ISSUE TITLE
Responsive Redesign // Tablet + Mobile Search, too many search features exposed for home pge and product pge templates

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo-project#189] opened 2020-02-27 18:52 UTC
![IMG_3669](https://user-images.githubusercontent.com/54991698/75475490-deef9180-5966-11ea-9bd9-26fe9954ab40.PNG)
@kkellydesign see above screen shot from my iOS device.
On the home page and then again on the products --- or further more globally -- when we have the large search field in the page as a primary element already, and then we pop open the search icon from the nav we get this doubling effect of the search that is a little jarring.

I've been trying to think through a logical and ideal fix but I'm torn.
I'd like to say -- could we turn off the search in the nav for those pages that have it as a primary element and have it re-appear when they scroll down, but I dont think that probably possible right now.
Let me know your thoughts @kkellydesign

**Comment by kkellydesign** [comment] 2020-02-27 20:56
This whole thing is a bit confusing on the UX side because we're using code that was designed for a full-screen desktop experience. It's all a bit more jarring when by necessity, the page jumps around a lot on mobile. That experience is exaggerated when more copy is added around the search field on the search results page. These new design elements make a lot of sense when it's a traditional URL-based search experience, but it takes a lot of JS to make the instant- search feature match these new designs, especially when instant-search wasn't really designed for mobile at all. 

I made one more minor edit so that the functionality lines up more closely with the existing site – as soon as you start typing, the other field is focused. I think this is the only compromise that doesn't require completely removing the search results page masthead on mobile. Let me know what you think of this.

![Screen Recording 2020-02-27 at 3 45 34 PM](https://user-images.githubusercontent.com/202590/75485492-c7210900-5978-11ea-9304-1d1dc0d25e10.gif)

**Comment by ovidiuboca1** [comment] 2020-03-10 13:09
I verified this on the IOS device (iPhone 8 plus)  and the functionality described by kelly is implemented. 
@jess-cook03 please take a look at this and if you are ok with the functionality we can close this and move it to ready to deploy.

**Comment by jess-cook03** [comment] 2020-03-10 19:25
@akatsoulas @kkellydesign @ovidiuboca1 
Can we swing this into the backlog for future ux improvements ?

**Comment by ovidiuboca1** [comment] 2020-03-11 08:59
@jess-cook03  It's fine for me to move it to the V2 redesign milestone.

**Comment by akatsoulas** [comment] 2021-04-27 11:19
Closing this issue as stale

**Closed by akatsoulas** 2021-04-27 11:19 UTC
