### ISSUE TITLE
[mobile, iPad] Each product is listed above the search results, instead of within a dropdown 

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/sumo-project#133] opened 2020-01-27 14:05 UTC
**STR:**
1. Navigate to https://test.sumo.mozit.cloud/en-US/
2. Enter a keyword in the search input field (e.g: "Firefox")

**Expected:**
Products are displayed in a dropdown, "Firefox" is the default selected product (as per [designs](https://app.zeplin.io/project/5db3524d3cd0612c5d2f78a9/screen/5e1ccef214110480bbdf61dd))

**Actual:**
All existing products are listed in the "Filter by product" section, user has to scroll down in order to see search results

**Env:**
iPhone X, iOS 13.3, Chrome, Firefox and Safari

**Note:**
**Similar issue happens on iPad, where the products are listed on the rights side (same as desktop), instead of in a dropdown, above the search results**

phone:
![photo_2020-01-27_15-45-01](https://user-images.githubusercontent.com/5293100/73180182-7a4dd680-411d-11ea-8320-95317fb02c77.jpg)

iPad:
![photo_2020-01-27_15-59-13](https://user-images.githubusercontent.com/5293100/73180852-d2390d00-411e-11ea-87fd-c1a160e438d8.jpg)

**Comment by kkellydesign** [comment] 2020-01-28 21:06
There are two issues here. For some reason the javascript isn't loading correctly on the testing server, but it's working for me locally. This may be related to the staticfiles issue since this is being compiled from several different places in bundles.py, but I'm not sure how to go about debugging that since it looks fine on my machine. Lets see if this persists after the staticfiles issue is fixed. 

Otherwise, I changed some things so that the sidebar folds up correctly on tablet sizes, so that breakpoint is now identical to mobile in that regard. 

This fix is in this PR: https://github.com/mozilla/kitsune/pull/4150

You can see the new layout here:

<img width="700" alt="Screen Shot 2020-01-28 at 4 05 21 PM" src="https://user-images.githubusercontent.com/202590/73305403-04627180-41e8-11ea-90e3-1abc783c2eb9.png">

**Comment by kkellydesign** [comment] 2020-02-11 15:18
This is ready to be tested again. https://test.sumo.mozit.cloud/en-US/

**Comment by ovidiuboca1** [comment] 2020-02-12 12:24
Tested on iPhone 8 using the same steps as in the description and the issue is still there, the "Filter by product" section has "All Products" selected by default, please see the designs https://app.zeplin.io/project/5db3524d3cd0612c5d2f78a9/screen/5e1ccef214110480bbdf61dd

Another issue: the "View All" section can't be selected.

**Comment by kkellydesign** [comment] 2020-02-19 21:36
Firefox should only be selected by default If you start the search from the Firefox page. From the homepage, it should search all products. You can see this functionality working correctly here, where "Firefox for Android" is selected by default: 
https://test.sumo.mozit.cloud/en-US/products/mobile

<img width="449" alt="Screen Shot 2020-02-19 at 4 33 39 PM" src="https://user-images.githubusercontent.com/202590/74878682-c0b9de00-5335-11ea-819f-4666a6e0b80e.png">

Also, I can select the "View All" link from the tab list.

**Comment by ovidiuboca1** [comment] 2020-02-20 07:15
I verified this using the https://test.sumo.mozit.cloud/en-US/products/mobile on iPhone 8 plus and I can confirm the fix.

**Closed** 2020-04-14 17:41 UTC
Labels: bug
