### ISSUE TITLE
Responsive Redesign / Mobile UI rendering line under selected tabs issue?

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo-project#190] opened 2020-02-27 18:57 UTC
![IMG_3666](https://user-images.githubusercontent.com/54991698/75476617-e57f0880-5968-11ea-9f1d-ac5276724644.PNG)
@kkellydesign see above how the grey line and blue highlight line are not sitting on top of one another?? 
Using iOS iphone XR

**Comment by kkellydesign** [comment] 2020-03-02 18:01
the border on tabs, and mobile tag heights are fixed in https://github.com/mozilla/kitsune/pull/4201

![IMG_DCBDF9666C67-1](https://user-images.githubusercontent.com/202590/75703693-f344ce80-5c85-11ea-94f3-acf2d1de1bca.jpeg)

<img width="818" alt="Screen Shot 2020-03-02 at 1 00 40 PM" src="https://user-images.githubusercontent.com/202590/75703705-fcce3680-5c85-11ea-8e97-73682709624c.png">

**Comment by jess-cook03** [comment] 2020-03-02 18:33
@kkellydesign confirming that I'm seeing the correct rendering now for the line/underline.

**Comment by jess-cook03** [comment] 2020-03-10 18:54
confirming this is fixed

**Comment by jess-cook03** [comment] 2020-03-10 19:43
@kkellydesign @akatsoulas 
Bringing this back around and linking it to this issue #223 
I'm seeing this again within the topics pages and the search pages -- whereever we use the tabs!
![IMG_3699](https://user-images.githubusercontent.com/54991698/76352757-f2471900-62e5-11ea-8a71-3c78c72bcf5f.PNG)

**Comment by kkellydesign** [comment] 2020-03-11 14:44
This is fixed again. I reintroduced the issue during the spacing work, because I had adjusted the padding on the tabs components without doing the same on the 'more' button. We're all set now: 

![IMG_88FF74217093-1](https://user-images.githubusercontent.com/202590/76429373-553bbd00-6385-11ea-9ad2-0d78fb4aacee.jpeg)

**Comment by ovidiuboca1** [comment] 2020-03-13 14:57
I verified this on the mobile device iPhone 8 plus and I can confirm the fix.

**Closed** 2020-04-15 07:02 UTC
Labels: bug
