### ISSUE TITLE
Markdown like syntax is not rendered properly in the KB articles

### ISSUE THREAD

**Issue by ovidiuboca1** [mozilla/sumo-project#307] opened 2020-03-27 12:49 UTC
STR
1. Go to https://support.allizom.org/en-US/kb/add-social-features-firefox-sidebar

ER: The syntax markdown is rendered properly.
AR: The syntax markdown is not rendered properly.

**Comment by kkellydesign** [comment] 2020-03-27 15:57
This will be fixed here: https://github.com/mozilla/kitsune/pull/4270
<img width="959" alt="Screen Shot 2020-03-27 at 11 48 55 AM" src="https://user-images.githubusercontent.com/202590/77774834-0e56f400-7022-11ea-9032-357fcd3d01da.png">

**Comment by ovidiuboca1** [comment] 2020-03-30 09:39
I tested this on desktop and I can confirm the fix.
Also, on mobile, I spotted this issue - 
![Skype_Picture_2020_03_30T09_34_47_110Z](https://user-images.githubusercontent.com/54845678/77897863-eadeb400-7282-11ea-8cd7-3c76c1dcd755.jpeg) the three lines icon and the Add-ons word are doubled. I don't think this a major issue so I will move this to Ready to deploy.
CC @akatsoulas @madasan Please take a look at this and change it if you consider this a major issue.

**Comment by ovidiuboca1** [comment] 2020-03-30 12:07
Also on desktop if you go to this page https://support.allizom.org/en-US/kb/how-do-i-set-sync-my-computer the menu button icon is doubled.

**Comment by LeoMcA** [comment] 2020-03-30 12:38
This is a major bug, it prevents logged out users from seeing an article customised to their browser/platform.

It's caused by this change here: https://github.com/mozilla/kitsune/commit/e7b30fcb5a1b139bd68ded8fee97d63c49475c69#diff-8f51a7ce7d7c0e1365d6151838128474

This prevents the `show_for` sidebar item being rendered, which includes the json for all the various product/platform combinations we have.

**Comment by ovidiuboca1** [comment] 2020-03-31 10:44
I tested this on Mac OS X 10.14, Windows 10 and mobile iPhone 8 plus and I can confirm the fix.

**Closed** 2020-04-15 07:07 UTC
Labels: blocks release, bug
